version: '3'
services:
  pointer:
    image: "sephto/pointing:mvp"
    ports: 
     - "9999:9999"
     - "80:80"
  activemq:
    image: "smaject/activemq"
    ports:
     - "5000:5000"
     - "8161:8161"
     - "61616:61616"
     - "61613:61613"
     - "61617:61617"
